services:
  ddareuwang:       # 컨테이너 이름(서비스명) : 내가 임의로 지정 가능
    build: .        # 이 위치(., 즉 현재 폴더)에 있는 Dockerfile을 사용해서 이미지를 빌드
    image: dev:1.0       # 이미지 이름: 이 경우에는 '이름:버전'으로 사용함
    container_name: ddareuwang-container
    ports:
      - "8080:8080"
    working_dir: /flask_server # 여기서 컨테이너 실행 시작
    volumes:
      - ./flask_server:/flask_server
    ## volumes: docker compose up 명령어를 실행하는 순간, 
    ## 로컬의 ./flask_server 디렉토리와 컨테이너의 /ddareuwang/flask_server 디렉토리가 연결됩니다.
    environment:
      - FLASK_ENV=development #실제 운영(배포) 시에는 FLASK_ENV=production으로 바꾸셔야 합니다.
    restart: always
    command: python app.py #flask_server가 working_dir이니까 바로 app.py 써도 됨
